version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssword
      POSTGRES_USER: admin
      POSTGRES_DB: reviews_api

  server:
    image: alecchampaign/server:1.0
    restart: always
    ports:
      - 3000:3000
