version: '3.7'

services:
  db:
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      -  # VOLUME TO MAP (DATA) :/var/lib/postgresql/data
      - type: bind
        source: ./database/api_data
        target: /api_data
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: # DATABASE PASSWORD
      POSTGRES_USER: # DATABASE USER
      POSTGRES_DB: reviews_api
  redis:
    image: redis
    volumes:
      - /home/alec/hack-reactor/sprints/week-9/kartify-api-reviews/src/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
  server:
    image: alecchampaign/server:redis
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - PORT= # PORT TO RUN SERVER ON
      - DB_USER= # DATABASE USER
      - DB_PASS= # DATABASE PASSWORD
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
    ports:
      - 4000:4000
