version: '3.7'

services:
  db:
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /home/alec/hack-reactor/docker-volumes:/var/lib/postgresql/data
      - type: bind
        source: ./database/api_data
        target: /api_data
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: # PASSWORD
      POSTGRES_USER: # USER
      POSTGRES_DB: # DB

  server:
    image: alecchampaign/server:beta
    restart: always
    depends_on:
      - db
    environment:
      - PORT= # PORT
      - DB_USER= # USER
      - DB_PASS= # PASS
      - DB_HOST=db
      - DB_PORT=5432

    ports:
      - 4000:4000
