version: '3.7'

services:
  db:
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /home/alec/hack-reactor/docker-volumes:/var/lib/postgresql/data
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: p@ssword
      POSTGRES_USER: admin
      POSTGRES_DB: reviews_api

  server:
    image: alecchampaign/server:4.0
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
