apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      server: redis
  template:
    metadata:
      labels:
        server: redis
        version: 3.2.5
    spec:
      containers:
        - name: redis
          image: redis:3.2.5
          resources:
            requests:
              memory: 400Mi
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      server: web
  template:
    metadata:
      labels:
        server: web
    spec:
      containers:
        - name: server
          image: alecchampaign/server:redis
          env:
            - name: REDIS_HOST
              value: redis-entrypoint
            - name: REDIS_PORT
              value: '6379'
            - name: DB_HOST
              value: <DATABASE IP>
            - name: DB_USER
              value: <DATABASE USER>
            - name: DB_PASS
              value: <DATABASE PASSWORD>
            - name: DB_PORT
              value: '5432'
            - name: PORT
              value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: server-entrypoint
  namespace: default
spec:
  type: LoadBalancer
  selector:
    server: web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: redis-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    server: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    server: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: default
subsets:
  - addresses:
      - ip: 0.0.0.1
    ports:
      - port: 5432
